/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiaDoClienteRouteImport } from './routes/dia-do-cliente'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RankingRouteImport } from './routes/ranking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDoClienteRoute = DiaDoClienteRouteImport.update({
  id: '/dia-do-cliente',
  path: '/dia-do-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dia-do-cliente': typeof DiaDoClienteRoute
  '/painel': typeof PainelRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dia-do-cliente': typeof DiaDoClienteRoute
  '/painel': typeof PainelRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dia-do-cliente': typeof DiaDoClienteRoute
  '/painel': typeof PainelRoute
  '/ranking': typeof RankingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dia-do-cliente' | '/painel' | '/ranking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dia-do-cliente' | '/painel' | '/ranking'
  id: '__root__' | '/' | '/dia-do-cliente' | '/painel' | '/ranking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiaDoClienteRoute: typeof DiaDoClienteRoute
  PainelRoute: typeof PainelRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-do-cliente': {
      id: '/dia-do-cliente'
      path: '/dia-do-cliente'
      fullPath: '/dia-do-cliente'
      preLoaderRoute: typeof DiaDoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiaDoClienteRoute: DiaDoClienteRoute,
  PainelRoute: PainelRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
